---
- block:
   - import_tasks: agent.yml
- rescue:
   - name: got an error during agent installation. Inform NodeManager
     mockfog_send_status:
       nodemanager: http://localhost:7474
       status: ERROR
     delegate_to: localhost
     become: no
     tags: bootstrap